version: "3.8"

# 6379 redis
# 8000 redis-controller
# 8001 sensor-query
# 8002 main-api
# 8003 web-scrapper

services:
  redis:
    image: redis:latest
    container_name: redis_db
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./volume:/data
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"

  redis_controller:
    build: ./redis-db
    container_name: redis_controller
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./redis-db/app:/app  # MOUNT kodu aplikacji do kontenera

  sensor-query:
    build: ./sensor-query
    container_name: sensor_query
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./sensor-query/app:/app/app  # montujemy kod aplikacji
    depends_on:
      - redis_controller

  web_scraper:
    build: ./web-scrapper
    container_name: web_scraper
    restart: always
    ports:
      - "8003:8003"
    depends_on:
      - redis_controller
    environment:
      - REDIS_CONTROLLER_URL=http://redis-controller:8000/electricity
    volumes:
      - ./web-scrapper/app:/app/app  # MOUNT kodu aplikacji
